---
title: "Data Vis 2 - Cleaning"
author: "Josh"
date: "2022-09-24"
output: html_document
---

```{r packages}
library(tidyverse)
library(readxl)
library(naniar)
library(stringi)
library(janitor)
library(fuzzyjoin)
```


# Utils

```{r utils}
locations <- read_csv('../charts/data/airport_locations.csv') %>% clean_names()
read_exc <- function(path, sheet, cells) {
  read_excel(path = path, sheet = sheet, range = cells) %>% 
    clean_names() %>% 
    rename(airport_name = 2) %>% 
    # Join with airport location data
    fuzzy_left_join(locations, by = c("airport_name" = "iata"), match_fun = stri_detect_fixed)
}
months
```

# Airport Arrival Rankings

```{r}
# airport_arr_rank_2020 <- read_exc('../charts/data/airport_arr_rankings.xlsx', 1, 'D4:F34')
# airport_arr_rank_2019 <- read_exc('../charts/data/airport_arr_rankings.xlsx', 2, 'D4:F34')
# airport_arr_rank_2018 <- read_exc('../charts/data/airport_arr_rankings.xlsx', 3, 'D3:F33')
# airport_arr_rank_2017 <- read_exc('../charts/data/airport_arr_rankings.xlsx', 4, 'D3:F33')
# airport_arr_rank_2016 <- read_exc('../charts/data/airport_arr_rankings.xlsx', 4, 'D3:F32')
```

# Airport Delay Causes

```{r}
delay_data <- read_csv('../charts/data/Airline_Delay_Cause.csv') %>% 
  clean_names() %>% 
  drop_na() %>% 
  separate(airport_name, into = c("location", "airport_name"), sep = ": ") %>% 
  rename(arr_delay_mins = arr_delay, 
         carrier_delay_mins = carrier_delay, 
         weather_delay_mins = weather_delay, 
         nas_delay_mins = nas_delay, 
         security_delay_mins = security_delay, 
         late_aircraft_delay_mins = late_aircraft_delay)
delay_10_data <- delay_data %>% 
  filter(airport %in% c('ATL', 'DFW', 'DEN', 'ORD', 'LAX', 'CLT', 'MCO', 'LAS', 'PHX', 'MIA')) 
```

```{r}
# Yearly on-time data
delay_cause_yearly <- delay_data %>% 
  group_by(year) %>% 
  summarise(delay_carrier = sum(carrier_ct)/sum(arr_flights) * 100,
            delay_late = sum(late_aircraft_ct)/sum(arr_flights) * 100,
            delay_security = sum(security_ct)/sum(arr_flights) * 100,
            delay_nas = sum(nas_ct)/sum(arr_flights) * 100,
            delay_weather = sum(weather_ct)/sum(arr_flights) * 100) %>% 
  pivot_longer(-year, names_to = "type", values_to = "value")

delay_cause_monthly <- delay_data %>% 
  group_by(year, month) %>% 
  summarise(delay_carrier = sum(carrier_ct)/sum(arr_flights) * 100,
            delay_late = sum(late_aircraft_ct)/sum(arr_flights) * 100,
            delay_security = sum(security_ct)/sum(arr_flights) * 100,
            delay_nas = sum(nas_ct)/sum(arr_flights) * 100,
            delay_weather = sum(weather_ct)/sum(arr_flights) * 100) %>% 
  pivot_longer(-c(year, month), names_to = "type", values_to = "value")

delay_cause_yearly_mins <- delay_data %>% 
  group_by(year) %>% 
  summarise(delay_carrier = sum(carrier_delay_mins),
            delay_late = sum(late_aircraft_delay_mins),
            delay_security = sum(security_delay_mins),
            delay_nas = sum(nas_delay_mins),
            delay_weather = sum(weather_delay_mins)) %>% 
  pivot_longer(-year, names_to = "type", values_to = "value")

delay_cause_monthly_mins <- delay_data %>% 
  group_by(year, month) %>% 
  summarise(delay_carrier = sum(carrier_delay_mins),
            delay_late = sum(late_aircraft_delay_mins),
            delay_security = sum(security_delay_mins),
            delay_nas = sum(nas_delay_mins),
            delay_weather = sum(weather_delay_mins)) %>% 
  pivot_longer(-c(year, month), names_to = "type", values_to = "value")
```

```{r}
# Top airports by on-time data (YTD 2022)
top_airports <- delay_data %>% 
  filter(year == 2022) %>% 
  group_by(airport) %>% 
  summarise(on_time = (1 - (sum(arr_del15)/sum(arr_flights))) * 100,
            arr_flights = sum(arr_flights)) %>% 
  filter(arr_flights > 10000) %>% 
  arrange(desc(on_time)) %>% 
  top_n(10, on_time) %>% 
  ungroup() %>% 
  left_join(delay_data %>% select(airport, airport_name), by = "airport") %>% 
  unique()

# Top airports by arrival flights (YTD 2022)
top_airports_flights <- delay_data %>% 
  filter(year == 2022) %>% 
  group_by(airport) %>% 
  summarise(arr_flights = sum(arr_flights)) %>% 
  filter(arr_flights > 1000) %>% 
  top_n(10, arr_flights) %>%
  arrange(desc(arr_flights)) %>% 
  left_join(locations %>% select(-airport), by = c("airport" = "iata")) %>%
  # Just to ensure name consistency
  left_join(delay_data %>% select(airport, airport_name), by = "airport") %>% 
  select(airport, airport_name, arr_flights, latitude, longitude) %>% 
  unique() %>% 
  mutate(rank = rank(desc(arr_flights)))
```

```{r}
# Yearly-monthly on-time data
monthly_ontime <- delay_data %>% 
  # mutate(month_name = month.abb[month]) %>% 
  filter(year != 2022) %>% 
  group_by(year, month) %>% 
  summarise(on_time = (1 - (sum(arr_del15)/sum(arr_flights))),
            delayed_flights = sum(arr_del15),
            flights = sum(arr_flights))

# Yearly on-time data
yearly_ontime <- delay_data %>% 
  # mutate(month_name = month.abb[month]) %>% 
  filter(year != 2022) %>% 
  group_by(year) %>% 
  summarise(on_time = (1 - (sum(arr_del15)/sum(arr_flights))),
            delayed_flights = sum(arr_del15),
            flights = sum(arr_flights))
```

```{r}
# Yearly top carrier on-time rankings
top_airlines_yearly <- delay_data %>% 
  group_by(year, carrier_name) %>% 
  summarise(on_time = (1 - (sum(arr_del15)/sum(arr_flights))),
            flights = sum(arr_flights)) %>% 
  slice_max(order_by = on_time, n = 3) %>% 
  arrange(year, desc(on_time)) %>% 
  ungroup()

top_airlines_yearly <- top_airlines_yearly %>% 
  filter(year >= 2012)

# Yearly top airport on-time rankings
top_airports_yearly <- delay_data %>% 
  group_by(year, airport_name) %>% 
  summarise(on_time = (1 - (sum(arr_del15)/sum(arr_flights))),
            flights = sum(arr_flights)) %>% 
  filter(flights > 10000) %>% 
  slice_max(order_by = on_time, n = 3) %>% 
  arrange(year, desc(on_time)) %>% 
  ungroup() %>% 
  select(-flights)

top_airports_yearly <- top_airports_yearly %>% 
  filter(year >= 2012)
```

```{r}
# Top airlines by airport
top_delay_causes <- delay_data %>% 
  filter(year == 2022) %>% 
  group_by(year, carrier_name) %>% 
  summarise(delay_carrier = sum(carrier_ct),
            delay_late = sum(late_aircraft_ct),
            delay_security = sum(security_ct),
            delay_nas = sum(nas_ct),
            delay_weather = sum(weather_ct)) %>% 
  ungroup() %>% 
  pivot_longer(-c(year, carrier_name), names_to = "type", values_to = "value") %>% 
  group_by(carrier_name) %>% 
  slice_max(order_by = value) %>% 
  ungroup() %>% 
  group_by(type) %>% 
  summarise(airlines = n())

airline_ontime_2022 <- delay_data %>% 
  filter(year == 2021) %>% 
  group_by(year, carrier_name) %>% 
  summarise(on_time = (1 - (sum(arr_del15)/sum(arr_flights))),
            flights = sum(arr_flights)) %>% 
  filter(flights > 10000) %>% 
  arrange(desc(on_time))

delay_data %>% 
  filter(year == 2019) %>% 
  group_by(year, airport_name) %>% 
  summarise(on_time = (1 - (sum(arr_del15)/sum(arr_flights))),
            flights = sum(arr_flights)) %>% 
  filter(flights > 10000) %>% 
  arrange(desc(flights))
```


# Export

```{r export}
write_csv(airport_arr_rank_2020 %>% slice_head(n = 10), '../charts/data/airport_arr_rank_2020.csv')
write_csv(delay_cause_monthly, '../charts/data/delay_cause_monthly.csv')
write_csv(delay_cause_yearly, '../charts/data/delay_cause_yearly.csv')
write_csv(delay_cause_monthly_mins, '../charts/data/delay_cause_monthly_mins.csv')
write_csv(delay_cause_yearly_mins, '../charts/data/delay_cause_yearly_mins.csv')
write_csv(top_airports, '../charts/data/top_airports.csv')
write_csv(top_airports_flights, '../charts/data/top_airports_flights.csv')
write_csv(monthly_ontime, '../charts/data/monthly_ontime.csv')
write_csv(yearly_ontime, '../charts/data/yearly_ontime.csv')
write_csv(top_airlines_yearly, '../charts/data/top_airlines_yearly.csv')
write_csv(top_airports_yearly, '../charts/data/top_airports_yearly.csv')
write_csv(airline_ontime_2022, '../charts/data/airline_ontime_2022.csv')
```

